### ISSUE TITLE
Camera model and stereo baseline for HIMB data

### ISSUE THREAD

**Issue by miloknowles** [kskin/data#2]
Hi - thanks for making the HIMB stereo data available here! Could you provide the camera intrinsics and stereo baseline for that dataset? Or information about the hardware platform you used?

Thanks,
Milo

**Comment by kskin** [comment]
Hi Milo,

The image provided are rectified. For converting disparity to depth, I
believe the focal length is 952.58 and the baseline between the cameras is
0.1939 m for both HIMB datasets.

**Comment by miloknowles** [comment]
Thank you!
